
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL LITERAL NAME NL OPERATION TYPEstring : long_string\n\t\t| short_stringlong_string : TYPE NAME EQUAL LITERAL OPERATION LITERAL NLshort_string : TYPE NAME EQUAL LITERAL NL'
    
_lr_action_items = {'TYPE':([0,],[4,]),'$end':([1,2,3,9,11,],[0,-1,-2,-4,-3,]),'NAME':([4,],[5,]),'EQUAL':([5,],[6,]),'LITERAL':([6,8,],[7,10,]),'OPERATION':([7,],[8,]),'NL':([7,10,],[9,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'string':([0,],[1,]),'long_string':([0,],[2,]),'short_string':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> string","S'",1,None,None,None),
  ('string -> long_string','string',1,'p_string','parser.py',25),
  ('string -> short_string','string',1,'p_string','parser.py',26),
  ('long_string -> TYPE NAME EQUAL LITERAL OPERATION LITERAL NL','long_string',7,'p_long_string','parser.py',30),
  ('short_string -> TYPE NAME EQUAL LITERAL NL','short_string',5,'p_short_string','parser.py',34),
]
